// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Arrow: typeof import('./src/components/icons/Arrow.vue')['default']
    Home: typeof import('./src/components/icons/Home.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    Person: typeof import('./src/components/icons/Person.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    TestComponent: typeof import('./src/components/TestComponent.vue')['default']
  }
}
